 - name: Slack Notification
        uses: action/checkout@v1
        uses:  action/slack@v1
        env:
           SLACK_CHANNEL: '#test'
           SLACK_COLOR: '#3278BD'
           SLACK_ICON: https://github.com/polaris.png?size=48
           SLACK_MESSAGE: 'Post Content :polaris:'
           SLACK_TITLE: Post Title
           SLACK_USERNAME: sirinoti
           SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
 runs:
  using: 'node12'
  main: 'dist/index.js'
