# This is a basic workflow to help you get started with Actions

name: slack

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  slack:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Slack Notification
      uses: actions/slack@v1
      env:
       SLACK_CHANNEL: '#test'
       SLACK_COLOR: '#3278BD' 
       SLACK_ICON: https://github.com/polaris.png?size=48
       SLACK_MESSAGE: 'Post Content :polaris:'
       SLACK_TITLE: Post Title
       SLACK_USERNAME: sirinoti
       SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
    
